### ISSUE TITLE
Backup file does not backup all the settings

### ISSUE THREAD

**Issue by Farbodart** [AIGODLIKE/gesture_helper#14]
Settings in the "property" tab in the addon does not come back..
things like: font size, radius and so on

**Comment by Farbodart** [comment]
It turns out that if you install the addon directly from blender it would work fine!! 
I wonder if there is a problem with blender or the zip file have a problem!!

PS: thank you for the addon. very handy indeed <3

**Comment by AlexanderSDiff** [comment]
> It turns out that if you install the addon directly from blender it would work fine!! I wonder if there is a problem with blender or the zip file have a problem!!
> 
> PS: thank you for the addon. very handy indeed <3
Hi. I expirience the similar issue. What you mean exactly by " install the addon directly from blender"? Installation via extension platform? Or semi-manual installation by providing the path to zip folder?
