### ISSUE TITLE
关于插件ui的建议

### ISSUE THREAD

**Issue by silv3rarr0w** [AIGODLIKE/gesture_helper#17]
1. 希望默认字号颜色这些设置可以以饼菜单为参考和blender内主题统一一些，现在的默认设置像是从别的地方暴力移植过来的一样。
2. 字和图标分辨率感觉不对，好像和界面里那个分辨率缩放有一定关系，我在2k屏幕下看分辨率像是1080的，字号也不会随分辨率缩放改变。
![image](https://github.com/user-attachments/assets/5cb3b3e5-a2af-4bcd-a426-90b6365bb200)
3. 虽然可以用工作区过滤插件，但还是希望加一个隐藏插件n面板的选项，因为设置好后那个面板基本用不到了。

**Comment by xmx-emm** [comment]
1.默认颜色可以更改
2.新版本会按ui缩放来显示
3.新版本将添加一个是否启用的属性
