### ISSUE TITLE
Gestures opened as empty

### ISSUE THREAD

**Issue by AlexanderSDiff** [AIGODLIKE/gesture_helper#18]
For some reason im stuck with this issue.
Fresh installation of blender 4.2.4 LTS.

Steps:
1. Adding custom keymap inherited from default Industry Compatible
2.  change some hotkeys (disabling T for transform tool, C for 3d cursor in mesh and object modes)
3. installing addons. Addon list: 

> io_anim_bvh
> io_curve_svg
> io_mesh_uv_layout
> io_scene_fbx
> io_scene_gltf2
> cycles
> pose_library
> bl_pkg
> bl_ext.blender_org.EdgeFlow
> bl_ext.blender_org.extra_curve_objectes
> bl_ext.blender_org.extra_mesh_objects
> bl_ext.blender_org.looptools
> LR_select
> ReBevel
> MACHIN3tools
> bl_ext.blender_org.edit_mesh_tools
> niche-loops_v1-0-2
> forgotten_tools
> kekit
> MESHmachine
> old_modifier_menu__favourites
> BakeMatcher
> fit_lattice
> hide_only_vertex_ver1-0-2
> rizomuv_bridge
> object_radial_tools
> Smart_Delete_v2
> Edge_Ring_Cuts
> mesh_merge_tool
> mesh-fairing-master
> vps_smoothing
> slide_edge
> subdivision_switch
> object_boolean_tools
> bl_ext.blender_org.copy_attributes_menu
> bl_ext.user_default.gesture_helper

4. installing Gestures Helper
5. Import Previously maded gestures

Since gesture addon was installed after all changes maded in keymap, it was mandatory to save keymap again to solve the issue with addon switch back to transform tool or 3d cursor.

At this state everything will work as expected until first restart of blender.
After restart attempts to run some gestures will show gestures as empty:
![scr](https://github.com/user-attachments/assets/8cd9f839-8e52-4e33-b366-0bb5306c67b0)

Full copy-paste of console after running the blender and pressing T once for open gesture. Im not sure does those warnings are related to gesture addon or something else:
Warning: property 'name' not found in item 'OperatorProperties'
Warning: property 'idname' not found in item 'OperatorProperties'
Warning: property 'method' not found in item 'OperatorProperties'
Warning: property 'type' not found in item 'OperatorProperties'
Warning: property 'type' not found in item 'OperatorProperties'
Warning: property 'type' not found in item 'OperatorProperties'
Warning: property 'blend_file' not found in item 'OperatorProperties'
Warning: property 'blend_file' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'index' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Warning: property 'objmode' not found in item 'OperatorProperties'
Warning: property 'flick' not found in item 'OperatorProperties'
Warning: property 'idname' not found in item 'OperatorProperties'
Warning: property 'inner' not found in item 'OperatorProperties'
Warning: property 'inner' not found in item 'OperatorProperties'
Warning: property 'deselect' not found in item 'OperatorProperties'
Warning: property 'deselect' not found in item 'OperatorProperties'
Warning: property 'rings' not found in item 'OperatorProperties'
Warning: property 'rings' not found in item 'OperatorProperties'
Warning: property 'objmode' not found in item 'OperatorProperties'
Warning: property 'transform_mode' not found in item 'OperatorProperties'
Warning: property 'sharp' not found in item 'OperatorProperties'
Warning: property 'offset' not found in item 'OperatorProperties'
Warning: property 'sharp' not found in item 'OperatorProperties'
Warning: property 'offset' not found in item 'OperatorProperties'
Warning: property 'sharp' not found in item 'OperatorProperties'
Warning: property 'offset' not found in item 'OperatorProperties'
Warning: property 'slideoverride' not found in item 'OperatorProperties'
Warning: property 'mode' not found in item 'OperatorProperties'
Warning: property 'slideoverride' not found in item 'OperatorProperties'
Warning: property 'mode' not found in item 'OperatorProperties'
Warning: property 'mergetype' not found in item 'OperatorProperties'
Warning: property 'slideoverride' not found in item 'OperatorProperties'
Warning: property 'mode' not found in item 'OperatorProperties'
Warning: property 'mergetype' not found in item 'OperatorProperties'
Warning: property 'slideoverride' not found in item 'OperatorProperties'
Warning: property 'mode' not found in item 'OperatorProperties'
Warning: property 'mergetype' not found in item 'OperatorProperties'
Warning: property 'slideoverride' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Warning: property 'idname' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'direction' not found in item 'OperatorProperties'
Warning: property 'include_selection' not found in item 'OperatorProperties'
Warning: property 'unhide' not found in item 'OperatorProperties'
Warning: property 'flick' not found in item 'OperatorProperties'
Warning: property 'remove' not found in item 'OperatorProperties'
Warning: property 'method' not found in item 'OperatorProperties'
Warning: property 'invert' not found in item 'OperatorProperties'
Warning: property 'method' not found in item 'OperatorProperties'
Warning: property 'invert' not found in item 'OperatorProperties'
Warning: property 'gesture' not found in item 'OperatorProperties'
Registered MACHIN3tools 1.11.1.DeusEx with 24 tools, 10 pie menus
Registered MESHmachine 0.17.0 with 2 plug libraries
 • plug library: Examples
 • plug library: MyPlugs
Imported fit_lattice
[DEBUG] (2024/11/28 16:54:03) mesh-fairing-master.linalg.init():L164 - Using NumPySolver
Registered Volume Preserving Smoothing
vps_smoothing
Gesture Clear Legacy Keymap count 6
Gesture -> Kmi Transform Helper (Type=T,Value=PRESS,Direction=ANY,Any=False,Shift=0,Ctrl=0,Alt=0,Oskey=0,Key_Modifier=NONE,Repeat=False)
invoke GESTURE_OT_operator      modal   PRESS   T       prev LEFTMOUSE RELEASE

**Comment by xmx-emm** [comment]
The new version has been fixed, please try if there is still this issue
https://github.com/AIGODLIKE/gesture_helper/releases/tag/v2.0.8
