### ISSUE TITLE
导入备份的一些问题。

### ISSUE THREAD

**Issue by Loiset** [AIGODLIKE/gesture_helper#19]
大佬，我现在用的是2.0.7版本，遇到一个问题，如果我在操作符类型里选择的是脚本，然后导出备份，再导入后会有警告，操作符选择为脚本的手势方向全部都回到了右下，然后操作符和操作符属性会是空的和整个红色显示，会有操作符错误的警告。
不过只需要修改手势方向，不管红色的警告也是可以正常使用的。
![QQ图片20241202101320](https://github.com/user-attachments/assets/d84b6471-d78e-4b35-b70c-653d04ea91a1)
[Uploading Gesture 2024-11-29 17 17 29.008830.json…]()

**Comment by Loiset** [comment]
查了下好像附件不支持json，我在传一次。
[Gesture 2024-11-29 17 17 29.008830.zip](https://github.com/user-attachments/files/17971745/Gesture.2024-11-29.17.17.29.008830.zip)

**Comment by xmx-emm** [comment]
![image](https://github.com/user-attachments/assets/5f9425f4-528a-4613-ac80-5343f5b52ebb)
根据导入的配置来看，是poll 设置的问题，如果没有这个属性的话会出现语法错误，这个属性可能是其它插件注册的，需要对属性不存在时进行处理

**Comment by xmx-emm** [comment]
现在poll出现语法错误不会直接进行提示，后续将会优化

**Comment by xmx-emm** [comment]
v2.0.8 已经添加了错误提示,如果不是Blender原属性需要使用getattr来获取属性,避免此属性不存在出现错误
```getattr(C.scene, "sna_blocksuracesmode",None )  == 'blocking' and C.scene.sna_addruning```
![image](https://github.com/user-attachments/assets/221ae21b-0c03-4993-8aae-466847b02c46)
https://github.com/AIGODLIKE/gesture_helper/releases/tag/v2.0.8
