### ISSUE TITLE
Will this add-on be added to the new Extension Platform? 

### ISSUE THREAD

**Issue by Dangry98** [AIGODLIKE/gesture_helper#2]
Hi, are there any plans to add this add-on to the new Blender Extension Platform? It would be a great way to make more people find this amazing add-on! 
https://extensions.blender.org/

**Comment by xmx-emm** [comment]
New features are being developed ，will be added later.

**Comment by xmx-emm** [comment]
It's uploaded to the review queue.
https://extensions.blender.org/approval-queue/gesture-helper/
