### ISSUE TITLE
Suggestion:  Could you add an optiont to hide it in N panel?

### ISSUE THREAD

**Issue by Farbodart** [AIGODLIKE/gesture_helper#20]
Once the add-on is set up, it does not require a dedicated panel in the user interface.
If you add an option to hide it in N-panel.. it would be great!

thank you for your work!

**Comment by xmx-emm** [comment]
2.0.8 version This option has been added
![image](https://github.com/user-attachments/assets/df34f0d6-fd89-4e0e-9102-bd5cf4be0b5b)

https://github.com/AIGODLIKE/gesture_helper/releases/tag/v2.0.8

**Comment by Farbodart** [comment]
I saw you've add it in your latest release!
Thank you
