### ISSUE TITLE
Hotkey bug in recent version.

### ISSUE THREAD

**Issue by Foulvertex** [AIGODLIKE/gesture_helper#21]
Hello, thanks for wonderful add-on!

My issue is that after enabling add-on, importing Maya Operator preset menu it works only for a session. After Blender restart, mapped hotkey doesn't work. If I manually add "**gesture.operator**" command with "_Maya Operator_" gesture parameter in 3DView (Global) it works as before.

**Comment by xmx-emm** [comment]
Does this error occur in version 2.0.8 and can it be triggered stably

**Comment by Foulvertex** [comment]
Seems like it's an interference from some other add-on on my install. On a clean 4.2 Blender all works perfectly. Sorry for bothering you...
