### ISSUE TITLE
热合助手改造建议

### ISSUE THREAD

**Issue by RXCsper** [AIGODLIKE/gesture_helper#3]
1、 Appearance style
1. It is recommended to add buttons for the "Free Layout" and "Draw" menus or commands on the editing page of the plugin.
2. It is recommended to add a free layout and drawing interface, which can be accessed by clicking the "button"
3. You can use Blender's built-in drawing module to draw and create menu appearance styles, and then convert the file to a special format, similar to a format that supports appearance editing
4. Alternatively, a new UI interface could be created, similar to the "Pen Tool" or "Shape Tool" in Ps or Blender Add the source code of the tool to the UI interface.
5. Then add a new format to the appearance style file, or use a conversion tool to convert it to the native supported format of the appearance
6. In the UI interface, you can add: pen, curve, shape, brush, brush style, pen pressure, pressure sensing mode Wait for the tool to define the appearance of the hot box menu
7. You can use the tools on the appearance editing page to customize the appearance style, number of slots, appearance style of the center hub of the hot box, position and suction force of the slots, automatic lighting of the slots when the mouse approaches them, and color after the slots are lit
7. It is recommended to add multiple styles of menu instances, such as list menus, rotatable roulette menus, square menus wait
8. Multiple menus can be nested within a pie menu, for example, placing the "List Menu" in a slot of the pie menu and adding "When the mouse moves to this slot, the internal menu or command will be automatically displayed", similar to an editable floating window.
9. The nested menu can also be directly displayed in the pie menu
10. You can add a button for editing pages in the sub gestures or operators on the right-hand side of the plugin, which allows you to enter nested menus on the editing page.
11. Add a label or folder function to the left menu display column to manage menus in various areas and classify them

**Comment by xmx-emm** [comment]
外观暂时不会有大的改动
