### ISSUE TITLE
反馈一个小问题

### ISSUE THREAD

**Issue by DENG-XC** [AIGODLIKE/gesture_helper#5]
在雕刻模式下，把draw sharp和clay strip笔刷设置为快捷手势后，无法工作，其他笔刷都能正常工作。

**Comment by xmx-emm** [comment]
ok，我看看

**Comment by xmx-emm** [comment]
修好了,这个是添加的时候操作符属性空格被替换了
下个版本发布,如果需要马上用的话下这个就好了,重新添加操作符
814a135c1489856995e51ad9bc962f1aae6a7fe2
