### ISSUE TITLE
 优化建议

### ISSUE THREAD

**Issue by XiaoXiong234** [AIGODLIKE/gesture_helper#8]
1.希望能给开关类型的手势添加一个视觉上的区分，举个例子，我往手势中添加了一个校正面属性的操作符，它不是能开能关吗，但是我无法通过热盒中的饼菜单看出它现在是开启还是关闭，我需要到选项下面查看，但是我既然要到选项下面查看，我也没必要将这个功能添加到手势里了
<img width="991" alt="企业微信截图_20240906182924" src="https://github.com/user-attachments/assets/11317a86-05f1-46e4-b390-ba23719936fa">
2.目前手势中对于子级的显示过于不明显，只有一个向下的小标以及最前面有一个结构一样的图标来表示，很容易在视觉上出现误判，还有这个选择按钮，有点反直觉，特别是在有子级的情况，父级是高亮显示的，但是操作没用，因为选择的其他子级的内容，视觉上也特别容易误判
![image](https://github.com/user-attachments/assets/2ab84a3d-28b9-46c7-9128-0a8fa403b7b9)
3.是否有考虑过添加一个"将多个操作符能按照自己喜好排序然后通过一个手势依次执行"的操作，举个简单的例子，就比如说我想给几个面的外轮廓标记缝合边，我可以通过“选择面”-“选择区域轮廓线”-“标记缝合边”这三步来实现，现在可以手动将2，3步放到一个手势中，通过在热盒中点击这个手势就会自动执行这两步,这样就能通过“选择面”-“手势”两步就能实现了

**Comment by xmx-emm** [comment]
1.这个是一个切换的操作符 bpy.ops.wm.context_set_boolean 是没有状态的
2.显示是使用blender 的uilist显示的,暂时没有更好的显示方法
3.这种批量执行是可以实现的,在操作符可以选择脚本模式,可以添加这种执行多个的操作符,不过需要一定的代码基础,有一些门槛

**Comment by xmx-emm** [comment]
下个版本会有布尔值 颜色提示
