### ISSUE TITLE
问题反馈：配置好的设置，在bl重启后，虽然配置还显示在菜单中，但相关快捷键命令失效。

### ISSUE THREAD

**Issue by WTianZuo** [AIGODLIKE/gesture_helper#9]
设置相关操作配置后 重启软件 插件手势功能会 失效。虽然显示配置还在。必须开关此插件（_开关插件也会导致相关配置消失_）重新导入配置才可以。
其他类似饼状操作插件context Pie和3D Viewport Pie Menus 及**Pie Menu Editor**设置后，下次重启还会保持最后设置的配置，重启即用。
因为工作中 还要用到插件管理类插件，所以像这种情况 很难配合管理插件使用。故特来反馈下，谢谢大佬的插件。让人体验到了maya般的丝滑！0.0

**Comment by WTianZuo** [comment]
已解决，设置后重新手动开关插件 然后保存配置文件即可

**Comment by WTianZuo** [comment]
使用cleanPanels的延迟加载后可以正常使用！！！已经满足我的使用需求了。谢谢！这个问题不再是困扰了，大佬是否关闭问题？

**Comment by xmx-emm** [comment]
2.0.4解决了退出Blender时的备份配置问题，如果还有这个问题的话需要远程确定问题点
如果还出现了这个问题再打开问题

https://github.com/AIGODLIKE/gesture_helper/releases/tag/v2.0.4

**Comment by xmx-emm** [comment]
如果还是出现这个问题那么需要关闭这个插件
3D Viewport Pie Menus
